import { Hono } from "hono";
import { pool, transaction } from "../db.js";
import { HttpError, requireCsrf } from "../security.js";
import { currentUser } from "../session.js";

export const productRoutes = new Hono();

async function ownedConversation(userId:string,id:string){
  const result=await pool.query(`SELECT * FROM app_conversations WHERE conversation_id=$1 AND user_id=$2 AND archived_at IS NULL`,[id,userId]);
  if(!result.rows[0]) throw new HttpError(404,"Conversation not found"); return result.rows[0];
}

productRoutes.get("/api/workspaces",async(c)=>{await currentUser(c);const result=await pool.query(`SELECT workspace_id,label,route,icon,status,sort_order FROM app_workspaces WHERE status='active' ORDER BY sort_order`);return c.json(result.rows);});

productRoutes.get("/api/users/me/settings",async(c)=>{const user=await currentUser(c);const result=await pool.query(`INSERT INTO user_settings(user_id) VALUES($1) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING theme,sidebar_collapsed,default_workspace_id,density,preferred_language,ui_preferences`,[user.user_id]);return c.json(result.rows[0]);});
productRoutes.patch("/api/users/me/settings",async(c)=>{requireCsrf(c);const user=await currentUser(c);const body=await c.req.json<Record<string,unknown>>();if(body.preferred_language!==undefined&&!['es','en'].includes(String(body.preferred_language)))throw new HttpError(422,"preferred_language must be es or en");const allowed=["theme","sidebar_collapsed","default_workspace_id","density","preferred_language","ui_preferences"];const fields=allowed.filter(k=>body[k]!==undefined&&body[k]!==null);await pool.query(`INSERT INTO user_settings(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING`,[user.user_id]);if(fields.length){const sets=fields.map((k,i)=>`${k}=$${i+2}`).join(",");await pool.query(`UPDATE user_settings SET ${sets},updated_at=now() WHERE user_id=$1`,[user.user_id,...fields.map(k=>body[k])]);}const result=await pool.query(`SELECT theme,sidebar_collapsed,default_workspace_id,density,preferred_language,ui_preferences FROM user_settings WHERE user_id=$1`,[user.user_id]);return c.json(result.rows[0]);});
productRoutes.get("/api/users/me/onboarding",async(c)=>{const user=await currentUser(c);const result=await pool.query<{ui_preferences:Record<string,unknown>}>("SELECT ui_preferences FROM user_settings WHERE user_id=$1",[user.user_id]);return c.json({completed:result.rows[0]?.ui_preferences?.onboarding_completed!==false});});
productRoutes.post("/api/users/me/onboarding",async(c)=>{requireCsrf(c);const user=await currentUser(c);const state=await pool.query<{ui_preferences:Record<string,unknown>}>("SELECT ui_preferences FROM user_settings WHERE user_id=$1",[user.user_id]);if(state.rows[0]?.ui_preferences?.onboarding_completed===true)throw new HttpError(409,"Onboarding already completed");const body=await c.req.json<Record<string,unknown>>();const weight=Number(body.weight_kg),height=Number(body.height_cm),age=Number(body.age);const activity=String(body.activity_level||""),goal=String(body.goal||"");if(!Number.isFinite(weight)||weight<30||weight>350||!Number.isFinite(height)||height<100||height>250||!Number.isInteger(age)||age<13||age>120||!["low","moderate","high"].includes(activity)||!["lose_fat","maintain","gain_muscle"].includes(goal))throw new HttpError(422,"Invalid onboarding fields");await transaction(async(db)=>{await db.query("INSERT INTO user_metric_entries(user_id,metric_type,label,recorded_at,value_number,unit,source,metadata_json) VALUES($1,'weight','Peso',now(),$2,'kg','onboarding','{}'),($1,'height','Estatura',now(),$3,'cm','onboarding','{}')",[user.user_id,weight,height]);await db.query("INSERT INTO user_preference_items(user_id,category,label,value,importance,status,source,metadata_json) VALUES($1,'goal','Objetivo',$2,5,'active','onboarding','{}'),($1,'schedule','Actividad',$3,4,'active','onboarding','{}'),($1,'goal','Edad',$4,3,'active','onboarding','{}') ON CONFLICT(user_id,category,label) DO UPDATE SET value=EXCLUDED.value,source='onboarding',updated_at=now()",[user.user_id,goal,activity,String(age)]);await db.query("INSERT INTO user_settings(user_id,ui_preferences) VALUES($1,'{\"onboarding_completed\":true}'::jsonb) ON CONFLICT(user_id) DO UPDATE SET ui_preferences=user_settings.ui_preferences || '{\"onboarding_completed\":true}'::jsonb,updated_at=now()",[user.user_id]);});return c.json({completed:true});});

productRoutes.get("/api/conversations",async(c)=>{const user=await currentUser(c);const r=await pool.query(`SELECT conversation_id,workspace_id,title,status,pinned,created_at,updated_at FROM app_conversations WHERE user_id=$1 AND archived_at IS NULL ORDER BY pinned DESC,updated_at DESC LIMIT 80`,[user.user_id]);return c.json(r.rows);});
productRoutes.post("/api/conversations",async(c)=>{requireCsrf(c);const user=await currentUser(c);const body=await c.req.json<Record<string,unknown>>();const workspace=typeof body.workspace_id==="string"?body.workspace_id:"chat";const ws=await pool.query(`SELECT 1 FROM app_workspaces WHERE workspace_id=$1 AND status='active'`,[workspace]);if(!ws.rowCount)throw new HttpError(404,"Workspace not found");const title=typeof body.title==="string"&&body.title.trim()?body.title.trim():"New conversation";const r=await pool.query(`INSERT INTO app_conversations(user_id,workspace_id,title) VALUES($1,$2,$3) RETURNING conversation_id,workspace_id,title,status,pinned,created_at,updated_at`,[user.user_id,workspace,title]);return c.json(r.rows[0],201);});
productRoutes.patch("/api/conversations/:id",async(c)=>{requireCsrf(c);const user=await currentUser(c);await ownedConversation(user.user_id,c.req.param("id"));const b=await c.req.json<Record<string,unknown>>();const r=await pool.query(`UPDATE app_conversations SET title=COALESCE($3,title),pinned=COALESCE($4,pinned),status=COALESCE($5,status),updated_at=now() WHERE conversation_id=$1 AND user_id=$2 RETURNING conversation_id,workspace_id,title,status,pinned,created_at,updated_at`,[c.req.param("id"),user.user_id,typeof b.title==="string"?b.title.trim()||null:null,typeof b.pinned==="boolean"?b.pinned:null,typeof b.status==="string"?b.status:null]);return c.json(r.rows[0]);});
productRoutes.delete("/api/conversations/:id",async(c)=>{requireCsrf(c);const user=await currentUser(c);await ownedConversation(user.user_id,c.req.param("id"));await pool.query(`UPDATE app_conversations SET archived_at=now(),status='archived',updated_at=now() WHERE conversation_id=$1`,[c.req.param("id")]);return c.body(null,204);});
productRoutes.get("/api/conversations/:id/messages",async(c)=>{const user=await currentUser(c);await ownedConversation(user.user_id,c.req.param("id"));const r=await pool.query(`SELECT message_id,conversation_id,role,status,content_text,created_at,updated_at,metadata_json FROM app_messages WHERE conversation_id=$1 ORDER BY created_at LIMIT 240`,[c.req.param("id")]);return c.json(r.rows);});

function profile(items:Array<{category:string;label:string;value:string}>){const out={goals:[] as string[],restrictions:[] as string[],preferences:[] as string[]};for(const item of items){const category=item.category.trim().toLowerCase(),value=item.value.trim()||item.label.trim();const target=["goal","goals","objective","objectives"].includes(category)?out.goals:["restriction","restrictions","allergy","allergies","medical"].includes(category)?out.restrictions:out.preferences;if(value&&!target.includes(value))target.push(value);}return out;}
productRoutes.get("/v1/me",async(c)=>{try{const user=await currentUser(c,true);const r=await pool.query(`SELECT category,label,value FROM user_preference_items WHERE user_id=$1 AND status='active' ORDER BY category,label`,[user.user_id]);const name=user.display_name||user.primary_email.split("@")[0];return c.json({id:user.user_id,email:user.primary_email,name,display_name:name,plan:"free",profile:profile(r.rows)});}catch(e){if(e instanceof HttpError&&e.status===401)return c.json({error:"unauthorized",message:"Invalid or expired token"},401);return c.json({error:"server_error",message:"Unable to load profile"},500);}});

function metricSeries(rows:any[]){const groups=new Map<string,any[]>();for(const row of rows)if(row.value_number!==null){const group=groups.get(row.metric_type)||[];group.push(row);groups.set(row.metric_type,group);}const priority:any={weight:10,sleep:20,energy:30,adherence:40};return [...groups.entries()].map(([type,items])=>{items.sort((a,b)=>+new Date(a.recorded_at)-+new Date(b.recorded_at));const delta=Number(items.at(-1).value_number)-Number(items[0].value_number),unit=items.at(-1).unit||"";return{metric_type:type,label:items.at(-1).label,unit:items.at(-1).unit,trend_label:delta>0?"Subiendo":delta<0?"Bajando":"Estable",change_label:`${delta>0?"+":""}${delta.toFixed(1)}${unit}`,points:items.map(i=>({x:new Intl.DateTimeFormat("es-CL",{day:"2-digit",month:"short"}).format(new Date(i.recorded_at)),value:Number(i.value_number),recorded_at:i.recorded_at}))};}).sort((a,b)=>(priority[a.metric_type]||99)-(priority[b.metric_type]||99));}
productRoutes.get("/api/users/me/health-overview",async(c)=>{const user=await currentUser(c);const [m,p]=await Promise.all([pool.query(`SELECT * FROM user_metric_entries WHERE user_id=$1 ORDER BY metric_type,recorded_at`,[user.user_id]),pool.query(`SELECT preference_id,category,label,value,importance,status,source,metadata_json FROM user_preference_items WHERE user_id=$1 AND status='active' ORDER BY category,label`,[user.user_id])]);const series=metricSeries(m.rows),by=Object.fromEntries(series.map((s:any)=>[s.metric_type,s]));const latest=(type:string):[string,string]=>{const s=by[type];if(!s)return["—","Sin datos suficientes todavía"];const point=s.points.at(-1);return[`${point.value}${s.unit||""}`,`${s.trend_label} · ${s.change_label} en 7 días`];};const cardDefinitions:Array<[string,string,string]>=[["Peso","weight","neutral"],["Sueño","sleep","positive"],["Adherencia","adherence","positive"],["Energía","energy","neutral"]];const cards=cardDefinitions.map(([label,type,tone])=>{const [value,detail]=latest(type);return{label,value,detail,tone};});const titles:any={nutrition:"Preferencias alimentarias",schedule:"Rutina y adherencia",communication:"Cómo debe responder Victus"};const grouped=new Map<string,any[]>();for(const item of p.rows){const group=grouped.get(item.category)||[];group.push(item);grouped.set(item.category,group);}const avoid=p.rows.find((i:any)=>/evitar|alergia/i.test(i.value));return c.json({summary_cards:cards,metrics:series,preference_groups:[...grouped].map(([category,items])=>({category,title:titles[category]||category,items:items.sort((a,b)=>b.importance-a.importance)})),nutrition_focus:[{title:"Proteína distribuida",detail:"Priorizar una fuente proteica en desayuno y almuerzo antes de optimizar detalles finos.",status:"active"},{title:"Restricciones primero",detail:avoid?.value||"No hay restricciones críticas declaradas todavía.",status:"guardrail"},{title:"Cena liviana",detail:"Mantener opciones simples para reducir fricción de adherencia durante la semana.",status:"planned"}],read_only:false,profile_label:null,profile_note:null});});
productRoutes.post("/api/users/me/metrics",async(c)=>{requireCsrf(c);const user=await currentUser(c);const b=await c.req.json<any>();if(!b.metric_type||!b.label)throw new HttpError(422,"metric_type and label are required");const r=await pool.query(`INSERT INTO user_metric_entries(user_id,metric_type,label,recorded_at,value_number,value_text,unit,source,notes,metadata_json) VALUES($1,$2,$3,COALESCE($4,now()),$5,$6,$7,$8,$9,$10) RETURNING metric_entry_id,metric_type,label,recorded_at,value_number,value_text,unit,source,notes,metadata_json`,[user.user_id,b.metric_type,b.label,b.recorded_at||null,b.value_number??null,b.value_text??null,b.unit??null,b.source||"manual",b.notes??null,JSON.stringify(b.metadata_json||{})]);return c.json(r.rows[0],201);});
productRoutes.post("/api/users/me/preferences",async(c)=>{requireCsrf(c);const user=await currentUser(c);const b=await c.req.json<any>();if(!b.category||!b.label||!b.value)throw new HttpError(422,"category, label and value are required");const r=await pool.query(`INSERT INTO user_preference_items(user_id,category,label,value,importance,status,source,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING preference_id,category,label,value,importance,status,source,metadata_json`,[user.user_id,b.category,b.label,b.value,b.importance||3,b.status||"active",b.source||"user",JSON.stringify(b.metadata_json||{})]);return c.json(r.rows[0],201);});
